stages:
  - build
  - test
  - deploy

variables:
  FPM_TEST_IMAGE: $CI_REGISTRY_IMAGE/fpm:test

build-fpm-test:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --compress -f ./Dockerfile -t $FPM_TEST_IMAGE .
    - docker push $FPM_TEST_IMAGE
  only:
    - merge_requests

php-unit-test:
  image: $FPM_TEST_IMAGE
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - vendor/
  script:
    - composer install
    - ./vendor/bin/codecept run unit $* --coverage --coverage-text --no-colors
  coverage: '/^\s+Lines:\s+(\d+.\d+%)/'
