version: '3.7'
services:
  fpm:
    build: .
    working_dir: /app
    restart: always
    volumes:
      - .:/app
    networks:
      - app-network
    depends_on:
      - mysql
      - memcached
      - rabbitmq
    environment:
      - TZ=America/New_York

  memcached:
    networks:
      - app-network
    restart: always
    image: memcached
    environment:
      - TZ=America/New_York

  app-setup:
    build: .
    networks:
      - app-network
    user: root
    working_dir: /app
    tty: true
    stdin_open: true
    command: /bin/bash -c "composer install ;sleep 10; php yii app/init --interactive=0"
    depends_on:
      - memcached
      - mysql
      - rabbitmq
    volumes:
      - .:/app
    environment:
      - TZ=America/New_York

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "9822:80"
      - "9823:8080"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
    depends_on:
      - fpm
      - rabbitmq
      - mysql
    networks:
      - app-network

  mysql:
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    image: mysql:8.0
    restart: always
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d/
      - ./docker/mysql/data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=currency_rates
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_pass
    ports:
      - "3320:3306"
    networks:
      - app-network

  rabbitmq:
    image: "rabbitmq:3-management"
    restart: always
    volumes:
      - rabbitmq_currency_rates_api:/var/lib/rabbitmq
    ports:
      - "5670:5672"
      - "15670:15672"
    networks:
      - app-network
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - TZ=America/New_York

#  worker-mails:
#    build: .
#    restart: always
#    networks:
#      - app-network
#    user: root
#    working_dir: /app
#    tty: true
#    stdin_open: true
#    command: /bin/bash -c "sleep 10;  ./yii send-email-queue-worker/listen"
#    depends_on:
#      - mysql
#      - rabbitmq
#      - memcached
#    volumes:
#      - .:/app
#    environment:
#      - TZ=America/New_York
#    deploy:
#      replicas: 2
#
#  cron:
#    build:
#      context: .
#      dockerfile: DockerfileCron
#    working_dir: /app
#    volumes:
#      - .:/app
#      - ./docker/cron/cron.log:/var/log/cron.log
#    networks:
#      - app-network
#    depends_on:
#      - mysql
#      - memcached
#      - rabbitmq
#    environment:
#      - TZ=America/New_York

networks:
  app-network:
    driver: bridge

volumes:
  mysql_currency_rates_api:
  rabbitmq_currency_rates_api:
