version: '3.7'

services:
  memcached:
    container_name: memcached-currency-rates
    networks:
      - currency-rates-network
    restart: always
    image: memcached
    environment:
      - TZ=America/New_York

  mysql:
    container_name: mysql-currency-rates
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    image: mysql:8.0
    restart: always
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d/
      - ./docker/mysql/data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=currency_rates
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_pass
    ports:
      - "3320:3306"
    networks:
      - currency-rates-network

  rabbitmq:
    container_name: rabbitmq-currency-rates
    image: "rabbitmq:3-management"
    restart: always
    volumes:
      - rabbitmq_currency_rates_api:/var/lib/rabbitmq
    ports:
      - "5670:5672"
      - "15670:15672"
    networks:
      - currency-rates-network
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - TZ=America/New_York

networks:
  currency-rates-network:
    driver: bridge

volumes:
  mysql_currency_rates_api:
  rabbitmq_currency_rates_api:
