version: '3.7'

services:
  fpm:
    build: .
    working_dir: /app
    restart: always
    volumes:
      - .:/app
    networks:
      - currency-rate-app-network
    environment:
      - TZ=America/New_York

  app-setup:
    build: .
    networks:
      - currency-rate-app-network
    user: root
    working_dir: /app
    tty: true
    stdin_open: true
    command: /bin/bash -c "composer install ;sleep 10; php yii app/init --interactive=0"
    volumes:
      - .:/app
    environment:
      - TZ=America/New_York

  nginx:
    container_name: nginx-subscriptions
    image: nginx:latest
    restart: always
    ports:
      - "9832:80"
      - "9833:8080"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
    networks:
      - currency-rate-app-network

  worker-mails:
    build: .
    restart: always
    networks:
      - currency-rate-app-network
    user: root
    working_dir: /app
    tty: true
    stdin_open: true
    command: /bin/bash -c "sleep 10;  ./yii send-email-queue-worker/listen"
    volumes:
      - .:/app
    environment:
      - TZ=America/New_York
    deploy:
      replicas: 1

  cron:
    build:
      context: .
      dockerfile: DockerfileCron
    working_dir: /app
    volumes:
      - .:/app
      - ./docker/cron/cron.log:/var/log/cron.log
    networks:
      - currency-rate-app-network
    environment:
      - TZ=America/New_York

#  k6:
#    image: grafana/k6:latest
#    volumes:
#      - ./tests/load-k6:/load-k6
#    entrypoint: [
#      "sh", "-c",
#      "k6 run /load-k6/subscription.js \
#      --out experimental-prometheus-rw=http://prometheus-currency-rates:9090/metrics/job/k6  \
#      -e K6_PROMETHEUS_RW_SERVER_URL=http://prometheus-currency-rates:9090/api/v1/write "
#    ]
#    networks:
#      - currency-rate-app-network

networks:
  currency-rate-app-network:
    external: true
