global:
  evaluation_interval: 1s
  scrape_interval: 1s

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: [ 'nginx:80' ]

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
