name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer

      - name: Validate PHP version
        run: php -v

      - name: Install dependencies
        run: composer install

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse -c phpstan.neon --memory-limit=256M

  phpunit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer

      - name: Validate PHP version
        run: php -v

      - name: Install dependencies
        run: composer install

      - name: Run Codeception Unit Tests
        run: ./vendor/bin/codecept run unit --coverage --coverage-html --coverage-xml

      - name: Show Coverage Percentage
        run: |
          COVERAGE=$(grep 'lines-' tests/_output/coverage/clover.xml | sed -E 's/.*lines-valid="([0-9]+)" lines-covered="([0-9]+)".*/\1 \2/' | awk '{ print ($2 / $1) * 100 }')
          echo "Coverage is $COVERAGE%"
          echo "##[set-output name=coverage;]$COVERAGE"

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: tests/_output/coverage
